### ISSUE TITLE
Add Assignment operators (ex. %+=%)

### ISSUE THREAD

**Issue by lauramaxwell** [prlitics/infixit#5]
Add a series of new operators based on the Python (and Java and CSS...) assignment operators. For example, the Python += operator adds two values together and assigns the final value to a variable. This operator is often used to add values to a counter variable that tracks how many times something has happened, or append a value to the end of an existing string variable. This syntax increases efficiency and readability and is less typing for the programmer :) 

When you use the addition assignment operator on a numeric variable, two numbers will be added. The resultant value will be assigned to the initial variable. Thus `variable_name %+=% value` would be equivalent to `variable_name <- variable_name + value`. The value of the variable you specify and the subsequent value must be of the same type and must be either a string or a number (integer/float). In the case of a string variable, `%+=%` acts like `paste0()` or `%+%`, with assignment.

Apart from the addition assignment operator, there are also assignment operators for subtraction, multiplication and division following the same syntax. These would all follow the infix syntax of %[operator]%.

If the package owner approves, work for this issue will be on the `assignment_ops` branch.

**Comment by prlitics** [comment]
Resolved via [807f8a0](https://github.com/prlitics/infixit/pull/6/commits/807f8a094026cd001c694a8b8758a5425c984139)
